version: "3"

services:
  postgres:
    container_name: postgres-hyperskills
    image: postgres:latest
    ports:
      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"

    restart: always
    environment:
      POSTGRES_USER_HOST: ${POSTGRESQL_HOST}
      POSTGRES_USER: '${POSTGRESQL_USER}'
      POSTGRES_PASSWORD: '${POSTGRESQL_PASSWORD}'
      POSTGRES_DB: '${POSTGRESQL_DATABASE}'
      PGPORT: '${POSTGRESQL_PORT}'
    networks:
      - postgres

  dbmate:
    links:
      - postgres:postgres
    container_name: dbmate-hyperskills
    image: amacneil/dbmate
    env_file:
      - .env
    networks:
      - postgres
    environment:
      DATABASE_URL: 'postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}?sslmode=disable'
    volumes:
      - ./db:/db
      - ./tools:/tools

networks:
  postgres:
    driver: bridge
